name: Test AI Teammate in Current Repo

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  test-local-action:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Test AI PR Review (Local Action)
        uses: ./
        with:
          azure_openai_endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY }}
          azure_openai_model_name: ${{ secrets.AZURE_OPENAI_MODEL_NAME }}
          review_depth: "expert"
          max_tokens: "2000"
          temperature: "0.7"
